%YAML:1.0

---
imu: 1
num_of_cam: 2
imu_topic: /camera/imu
image0_topic: /camera/infra1/image_rect_raw
image1_topic: /camera/infra2/image_rect_raw
output_path: /root/D435i/output/

Camera.type: "PinHole"
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.fx: 383.692
Camera.fy: 383.692
Camera.cx: 316.978
Camera.cy: 239.796

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0
Camera2.fx: 383.692
Camera2.fy: 383.692
Camera2.cx: 316.978
Camera2.cy: 239.796

Camera.width: 640
Camera.height: 480
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0
Camera.fps: 30
Camera.bf: 40.0
Stereo.b: 0.0499585
ThDepth: 40.0
Camera.imageScale: 0.5
IMU.InsertKFsWhenLost: 0

IMU.NoiseGyro: 1e-3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1e-2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1e-6 # rad/s^1.5
IMU.AccWalk: 1e-4 # m/s^2.5
IMU.Frequency: 200

estimate_extrinsic: 1

IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.0, 0.0, 0.0, -0.00552,
          0.0, 1.0, 0.0, 0.0051,
          0.0, 0.0, 1.0, 0.01174,
          0.0, 0.0, 0.0, 1.0]
IMU.T_b_c2: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.0, 0.0, 0.0, 0.446571,
          0.0, 1.0, 0.0, 0.0051,
          0.0, 0.0, 1.0, 0.01174,
          0.0, 0.0, 0.0, 1.0]

ORBextractor.nFeatures: 1250
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [1,0,0,-0.005,
         0,1,0,-0.005,
         0,0,1,0.0117,
         0.0, 0.0, 0.0, 1.0]
Tlr: !!opencv-matrix
  rows: 3
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, 0.0499585,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]
Rectification.fx: 383.692
Rectification.fy: 383.692
Rectification.cx: 316.978
Rectification.cy: 239.796
Rectification.k1: 0.0
Rectification.k2: 0.0
Rectification.p1: 0.0
Rectification.p2: 0.0

multiple_thread: 1
max_cnt: 150
min_dist: 30
freq: 10
F_threshold: 1
show_track: 1
flow_back: 1
max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 10
acc_n: 0.1
gyr_n: 0.01
acc_w: 0.001
gyr_w: 0.0001
g_norm: 9.805
estimate_td: 1
td: 0
load_previous_pose_graph: 1
pose_graph_save_path: /root/D435i/output/pose_graph/
save_image: 1




Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0